fixtures:
  repositories:
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "1.7.0"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "1.1.2"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.4.0"
  symlinks:
    oracle_java: "#{source_dir}"

